version: "3"

services:
  cache:
    image: redis:5.0
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'

  postgres_db:
    image: postgres:12.0
    restart: always
    ports:
     - '5432:5432'
    expose:
     - '5432'
    volumes: 
      - volume-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: inf349

volumes:
  volume-postgres:



